baseURL = "/hugo-theme-serial-programmer/"
languageCode = "en-us"
title = "brownbear29"
rssLimit = 20
copyright = "2022 brownbear29"
minify = false

[Author]
  name = "brownbear29"
  email = ""

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]
